services:
  db:
    image: mysql:8.0
    container_name: mysql_core_container
    restart: always
    environment:
      MYSQL_DATABASE: core
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      # Se requiere una contraseña para el usuario root
      MYSQL_ROOT_PASSWORD: root_password 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: