{{- if .Values.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
type: Opaque
data:
  {{- range $key, $val := .Values.secret }}
  {{- $s := $val | toString }}
  {{ $key }}: {{ if contains "{{" $s }}{{ tpl $s $ | quote }}{{ else }}{{ $s | quote }}{{ end }}
  {{- end }}
{{- end }}
